repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-symlinks
      - id: pretty-format-json
      - id: check-json
      - id: check-case-conflict
      - id: check-added-large-files
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.13.1
    hooks:
      - id: stylua
