require("load-all")(os.getenv("HOME") .. "/.config/nvim/lua/config")
require("nvim-autopairs").setup()
require("colorizer").setup()
require("lsp")
require("fidget").setup()
require("lsp_signature").setup()
